# This workflow will tag a release on github when the package.json version changes on master, and publish package to npm and github

name: Test & Release

on: [ push,  pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  release:
    name: Release
    needs: [ test ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: justincy/github-action-npm-release@2.0.2

      - uses: actions/setup-node@v2
        if: steps.release.outputs.released == 'true'
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        if: steps.release.outputs.released == 'true'
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v2
        if: steps.release.outputs.released == 'true'
        with:
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        if: steps.release.outputs.released == 'true'
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
